version: '3.8'

services:
  service1:
    build: ./service_1
    container_name: service1
    expose:
      - "8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 10s
      timeout: 3s
      retries: 3

  service2:
    build: ./service_2
    container_name: service2
    expose:
      - "8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      service1:
        condition: service_healthy
      service2:
        condition: service_healthy
